{{- if eq (include "mariadb.createSecret" .) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  mariadb-root-password: {{ include "mariadb.rootPassword" . | b64enc | quote }}
  {{- if (not (empty .Values.auth.username)) }}
  mariadb-password: {{ include "mariadb.password" . | b64enc | quote }}
  {{- end }}
  {{- if eq .Values.architecture "replication" }}
  mariadb-replication-password: {{ include "mariadb.replicationPassword" . | b64enc | quote }}
  {{- end }}
{{- end }}
